on:
  push:
    branches: ['main']
jobs:
  analysis:
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: 'actions/checkout@v4'

      - name: 'Set Up JDK 17'
        uses: 'actions/setup-java@v4'
        with:
          distribution: 'corretto'
          java-version: 17

      - name: 'Setup Gradle'
        uses: 'gradle/actions/setup-gradle@v4'

      - name: 'Build with Gradle'
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
          echo "### build success ###"
